### ISSUE TITLE
Add note how hompage url can be added wiht pyproject.toml

### ISSUE THREAD

**Issue by neumantm** [Simulation-Software-Engineering/diffusion2d#2]
It is hard to find in the docs.
One needs to add the following section
```toml
[project.urls]
homepage = "<link>"
```
